# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2e25adc04461b7993b4c5764d2206fb89fe5db396f3cf67bd13665853487831cee3d9585d7c94a87c1dfeb0ed6e6754547241b3274dc104ed798fbae8b3654b2

test:
  secret_key_base: 667ba5bf26db98911b9783f007582b4e34ab810933beb6df7aca099218fbddf1ec683eca62c7239f35e69390489e173b8763bfbb4a4b5f462ec312f8e30a6f73

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
